import Head from 'next/head';
import { Carousel, Container } from 'react-bootstrap';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import trailer1 from '../public/dummy/carousel-trailer-1.jpg';
import trailer2 from '../public/dummy/carousel-trailer-2.jpg';
import trailer3 from '../public/dummy/carousel-trailer-3.jpg';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>시네마</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid className="p-0">
        <Carousel>
          <Carousel.Item>
            <Image
              src={trailer1}
              className="d-block w-100"
              alt="리미트 트레일러"
            />
          </Carousel.Item>
          <Carousel.Item>
            <Image
              src={trailer2}
              className="d-block w-100"
              alt="불릿트레인 트레일러"
            />
          </Carousel.Item>
          <Carousel.Item>
            <Image
              src={trailer3}
              className="d-block w-100"
              alt="한산 트레일러"
            />
          </Carousel.Item>
        </Carousel>
      </Container>
    </div>
  );
}
